site:
  'synthea_54':
    display_name: 'Synthea Synthetic Data'
    gcs_bucket: 'synthea_cdm54'
    file_delivery_format: '.csv'
    project_id: 'nih-nci-dceg-connect-dev'
    cdm_bq_dataset: 'synthea_cdm54'
    analytics_bq_dataset: 'synthea_atlas_results'
    omop_version: '5.4'
    date_format: '%Y-%m-%d'
    datetime_format: '%Y-%m-%d %H:%M:%S'
    overwrite_site_vocab_with_standard: true
    post_processing: ['']
  'synthea_testing':
    display_name: 'Synthea Synthetic Data'
    gcs_bucket: 'synthea_testing'
    file_delivery_format: '.csv'
    project_id: 'nih-nci-dceg-connect-dev'
    cdm_bq_dataset: 'synthea_testing'
    analytics_bq_dataset: 'synthea_testing_atlas_results'
    omop_version: '5.3'
    date_format: '%Y-%m-%d'
    datetime_format: '%Y-%m-%d %H:%M:%S'
    overwrite_site_vocab_with_standard: false
    post_processing: ['']